In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import pandas as pd
import numpy as np

In [3]:
mtcars = pd.read_csv(r'C:\Users\gustavofb\Documents\teste_ia\data_archives\mt_cars.csv')
mtcars.head()

Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [5]:
x = mtcars[['mpg', 'hp']].values
y = mtcars[['cyl']].values

In [7]:
knn = KNeighborsClassifier(n_neighbors=3)
modelo = knn.fit(x, y)

c:\Users\gustavofb\Documents\teste_ia\.venv\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [8]:
y_prev = modelo.predict(x)
print(y_prev)

[6 6 4 6 8 6 8 4 4 6 6 8 8 8 8 8 8 4 4 4 4 8 8 8 8 4 4 4 8 8 8 6]


In [9]:
acccuracy = accuracy_score(y, y_prev)
precision = precision_score(y, y_prev, average='weighted')
recall = recall_score(y, y_prev, average='weighted')
f1 = f1_score(y, y_prev, average='weighted')
cm = confusion_matrix(y, y_prev)

print(f"Acurácia: {acccuracy}, precisão: {precision}, recall: {recall}, f1: {f1}")
print(f"Matriz de confusão: {cm}")

Acurácia: 0.9375, precisão: 0.9395833333333333, recall: 0.9375, f1: 0.9372947454844006
Matriz de confusão: [[10  1  0]
 [ 0  6  1]
 [ 0  0 14]]


In [11]:
new_data = np.array([[19.3,105]])

previsao = modelo.predict(new_data)
print(previsao)

distances, indices = modelo.kneighbors(new_data)
print(distances)
print(indices)

[6]
[[1.2        4.5177428  5.28109837]]
[[ 5 31  1]]


In [13]:
mtcars.loc[[1,5,31], ["cyl", "mpg", "hp"]]

cyl   mpg   hp
1     6  21.0  110
5     6  18.1  105
31    4  21.4  109